### ISSUE TITLE
[ISSUE] Low efficiency when running cleaning script

### ISSUE THREAD

**Issue by jacklanda** [TeMU-BSC/corpus-cleaner-acl#1]
# Issue desc
When I try to run this clean.py script in the repo, I found my program can only process the text file under than 10MB around. Once the text file as input grow up to GB level in size, the cleaning process seems to be too slow to handle these large-scale data.

# Details
I do a simple test on my to-be-processed text file which is 2.1GB, it's shown that almost will take 1 month to run this script continually to finish it. It is to long to wait for this result. **n.b. I have passed the `--parallel` arg to script, but it still too slow.**

# Ask for help
How can I speed up this text preprocessing script? 

Thanks so much!

**Comment by JoanLlop** [comment]
Hi, could you share the exact command you're using, also if it's possible could you share a sample of the data (or the data) so we can reproduce your error?
Thanks

**Comment by asier-gutierrez** [comment]
IIRC the Corpus Cleaner tool **does not** divide the corpus into pieces. ¿Is your corpus splitted into files of similar size? You need to divide your corpus to at least as many files as the number of CPU cores you want to use.

Additionally, if you are running the tool in a virtualized environment (e.g. Docker), make sure you are allowing the tool to use as many CPU cores as needed.

**Comment by jacklanda** [comment]
Have addressed this issue by @asier-gutierrez 's advise. This only reason is that I've not splitted my to be processed text file into several part in the input dir, this cause very low efficiency. Now I've splitted it and run over the files using multiple  CPU cores. It makes me feel good :) Thanks.

**Comment by jacklanda** [comment]
I've found the key point in this issue, thank you so much !

**Comment by jacklanda** [comment]
**Another irrelevant question on this corpus cleaning script:**
Can this scirpt auto remove the noisy text like email, url, html tags, etc. in input text files? I've not found any relative args to open this kind of function.

**Comment by asier-gutierrez** [comment]
Hi @jacklanda I do not think it is an irrelevant question 🙂

According to the parameterization from the README.md file (https://github.com/TeMU-BSC/corpus-cleaner-acl#arguments):
 `[--no-replace-emails] [--no-remove-hashtags-mentions] [--no-remove-tags]  [--no-replace-urls]`
 
 Corpus Cleaner will perform these replacements by default unless you use the parameters defined above:
- Emails -> [EMAIL] https://github.com/TeMU-BSC/corpus-cleaner-acl/blob/90937b6c4acfefba22eaeb4e7a0d3cf61fc0e9c7/corpus_cleaner/components/c_pre_filterer/pre_filterer.py#L156
- URLs -> [URL] https://github.com/TeMU-BSC/corpus-cleaner-acl/blob/90937b6c4acfefba22eaeb4e7a0d3cf61fc0e9c7/corpus_cleaner/components/c_pre_filterer/pre_filterer.py#L192
- Hashtags -> " " (space char) https://github.com/TeMU-BSC/corpus-cleaner-acl/blob/90937b6c4acfefba22eaeb4e7a0d3cf61fc0e9c7/corpus_cleaner/components/c_pre_filterer/pre_filterer.py#L161
- HTML tags -> removal https://github.com/TeMU-BSC/corpus-cleaner-acl/blob/90937b6c4acfefba22eaeb4e7a0d3cf61fc0e9c7/corpus_cleaner/components/c_pre_filterer/pre_filterer.py#L356

In case you want to remove the documents that contain [EMAIL] you can do after the Cleaning process. The same applies for URLs. In the case of hashtags you will probably need to change the code in the place I pointed out by "[HASHTAG]" or something like that. In the case of HTML tags you should take into account that some of them are unary (e.g. br) and others are surrounding something (that could also be another tag).

**Comment by jacklanda** [comment]
> Hi @jacklanda I do not think it is an irrelevant question 🙂
> 
> According to the parameterization from the README.md file (https://github.com/TeMU-BSC/corpus-cleaner-acl#arguments): `[--no-replace-emails] [--no-remove-hashtags-mentions] [--no-remove-tags] [--no-replace-urls]`
> 
> Corpus Cleaner will perform these replacements by default unless you use the parameters defined above:
> 
>     * Emails -> [EMAIL] https://github.com/TeMU-BSC/corpus-cleaner-acl/blob/90937b6c4acfefba22eaeb4e7a0d3cf61fc0e9c7/corpus_cleaner/components/c_pre_filterer/pre_filterer.py#L156
> 
>     * URLs -> [URL] https://github.com/TeMU-BSC/corpus-cleaner-acl/blob/90937b6c4acfefba22eaeb4e7a0d3cf61fc0e9c7/corpus_cleaner/components/c_pre_filterer/pre_filterer.py#L192
> 
>     * Hashtags -> " " (space char) https://github.com/TeMU-BSC/corpus-cleaner-acl/blob/90937b6c4acfefba22eaeb4e7a0d3cf61fc0e9c7/corpus_cleaner/components/c_pre_filterer/pre_filterer.py#L161
> 
>     * HTML tags -> removal https://github.com/TeMU-BSC/corpus-cleaner-acl/blob/90937b6c4acfefba22eaeb4e7a0d3cf61fc0e9c7/corpus_cleaner/components/c_pre_filterer/pre_filterer.py#L356
> 
> 
> In case you want to remove the documents that contain [EMAIL] you can do after the Cleaning process. The same applies for URLs. In the case of hashtags you will probably need to change the code in the place I pointed out by "[HASHTAG]" or something like that. In the case of HTML tags you should take into account that some of them are unary (e.g. br) and others are surrounding something (that could also be another tag).

It helps me a log, sincerely appreciate your detailed intro & advise. Thanks so much!!!

**Comment by jacklanda** [comment]
By the way, it's possible that I can output the results text file in the format of document? (Input files are document-level text) I only found  `--output-format` can only be set as 'sentence' and 'fairseq-lm' ? Thanks.

**Comment by asier-gutierrez** [comment]
Hi @jacklanda you are right, it can only be set to 'sentence' and 'fairseq-lm' . However, it should not be difficult to implement a new one here: https://github.com/TeMU-BSC/corpus-cleaner-acl/tree/main/corpus_cleaner/components/i_output_formatter

Maybe the contributors can help you because I am not aware of all the architecture: @onadegibert @jordiae @ccasimiro88

Btw just noticed that this is not the latest version. It is the following one: https://github.com/PlanTL-GOB-ES/corpus-cleaner

**Comment by jacklanda** [comment]
> Hi @jacklanda you are right, it can only be set to 'sentence' and 'fairseq-lm' . However, it should not be difficult to implement a new one here: https://github.com/TeMU-BSC/corpus-cleaner-acl/tree/main/corpus_cleaner/components/i_output_formatter
> 
> Maybe the contributors can help you because I am not aware of all the architecture: @onadegibert @jordiae @ccasimiro88
> 
> Btw just noticed that this is not the latest version. It is the following one: https://github.com/PlanTL-GOB-ES/corpus-cleaner

I see, thanks for all your advise so much :)

**Comment by jordiae** [comment]
> > Hi @jacklanda you are right, it can only be set to 'sentence' and 'fairseq-lm' . However, it should not be difficult to implement a new one here: https://github.com/TeMU-BSC/corpus-cleaner-acl/tree/main/corpus_cleaner/components/i_output_formatter
> > Maybe the contributors can help you because I am not aware of all the architecture: @onadegibert @jordiae @ccasimiro88
> > Btw just noticed that this is not the latest version. It is the following one: https://github.com/PlanTL-GOB-ES/corpus-cleaner
> 
> I see, thanks for all your advise so much :)

fairseq-lm is a document-level format. Cheers.
